version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test-triangles:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |
            pip install pytest
            pytest --junitxml=test-results/junit.xml HW-02a/Triangle567/TestTriangle.py
      - store_test_results:
          path: test-results
    
  build-and-test-api:
    docker:
      -image: cimg/python:3.10.2
    steps:
      -checkout
      -run:
          command: |
            pip install pytest
            pytest --junitxml=test-results/junit.xml HW-04a/TestGitHubAPI.py
      -store_test_results:
          path: test-results

workflows:
  testing_triangles:
    jobs:
      - build-and-test-triangles

  testing_api:
    jobs:
      - build-and-test-api
